POST http://localhost:3001/api/deliverynote HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2YyYzJjZmFmOTFiOTc5NjYwOWZhZjQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDQ5Mjc2NDYsImV4cCI6MTc0NDkzNDg0Nn0.8WTK_qpgqxc7I7tTxwtwepcOOFaGjej0hhhJsbRDF9c

{
    "clientId": "67f54d6b86271c31199a2e9e",
    "projectId": "67facd7bd1de8890e7600b29",
    "format": "material",
    "material": "wood",
    "hours": 8,
    "description": "my description",
    "workdate": "2/1/2024"
}

###
GET http://localhost:3001/api/deliverynote/67facd7bd1de8890e7600b29 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2YyYzJjZmFmOTFiOTc5NjYwOWZhZjQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDQ2NTE4MjQsImV4cCI6MTc0NDY1OTAyNH0.YgaFxdLFB-57yyxxqRhHB3pE1krGepqT6WKgdqIkIYc

###
GET http://localhost:3001/api/deliverynote/ById/67fd5222f63cb4548b0ac142 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2YyYzJjZmFmOTFiOTc5NjYwOWZhZjQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDQ2NjU2MDgsImV4cCI6MTc0NDY3MjgwOH0.wZ6Sp0dlVPlQhYw3uZZz4I_OEtDWhteTAGjn1LhwOAE

###
GET http://localhost:3001/api/deliverynote/pdf/67fd5222f63cb4548b0ac142 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y1NGU4MWMwZmIzZjlmMTk5NDk5ZmUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDQ3MjEyNzYsImV4cCI6MTc0NDcyODQ3Nn0.X9_MNqtRWoXLo75pQ-DEujIMIA0N_sp2fKPnpw8VtEo

###

PATCH http://localhost:3001/api/deliverynote/signimage/67fd5222f63cb4548b0ac142 HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2YyYzJjZmFmOTFiOTc5NjYwOWZhZjQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDQ3Mzc4MzcsImV4cCI6MTc0NDc0NTAzN30.P89hVnp3Wp54EmUAtzr3dUqRrQoMSW3OeqLreKWa4xU

--boundary123
Content-Disposition: form-data; name="image"; filename="firma.png"
Content-Type: image/jpeg

< ./firma.png
--boundary123--

###
PATCH http://localhost:3001/api/deliverynote/signedPdf/67fd5222f63cb4548b0ac142 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2YyYzJjZmFmOTFiOTc5NjYwOWZhZjQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDQ4MDUyMzIsImV4cCI6MTc0NDgxMjQzMn0.5yEFf53dSPMsQ-wiEzB8ymaV6zCzZdNgblt7Dt0Si0E

###
DELETE http://localhost:3001/api/deliverynote/delete/67ffe3fde9a3026a3189313f HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2YyYzJjZmFmOTFiOTc5NjYwOWZhZjQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDQ4MjMyMTYsImV4cCI6MTc0NDgzMDQxNn0.vs2HPB_FCSz9LvsLBM_d2hsMIe0cL-APBT8PapiByx0