POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "mail": "primer@correo.es",
    "passwd": "A12345678"
}


###
POST http://localhost:3001/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "mail": "NoAutonomo@correo.es",
    "passwd": "A12345678"
}

###
POST http://localhost:3001/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "mail": "ahoraConToken@correo.es",
    "passwd": "A12345678"
}

###
POST http://localhost:3001/api/verify HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U5OGI2ZmQwM2ZhZGQ3MTczNzkwNjIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDMzNTg4MzIsImV4cCI6MTc0MzM2NjAzMn0.ECmiDeZxRPoyaA37TIbCRuLpm9qhHpOqI1NMItIXP5I

{
    "verifyCode": "423036"
}

###
POST http://localhost:3001/api/verify HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U5ODk5ZmQxZTY2OWIwZWRhZjc0YjQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDMzNTg1NTcsImV4cCI6MTc0MzM2NTc1N30.0yiaNULYkOKp7gRq7Sods7FtGbl_QKp9ADCn697v_zE

{
    "mail": "autonomo@correo.es",
    "verifyCode": "553027"
}

###
POST http://localhost:3001/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "mail": "autonomo@correo.es",
    "passwd": "A12345678"
}

####

PUT http://localhost:3001/api/users/register HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U5OGI2ZmQwM2ZhZGQ3MTczNzkwNjIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDMzNTg4MzIsImV4cCI6MTc0MzM2NjAzMn0.ECmiDeZxRPoyaA37TIbCRuLpm9qhHpOqI1NMItIXP5I

{
    "mail": "NoAutonomo@correo.es",
    "name": "José",
    "surnames": "García Pérez",
    "nif": "40000000W"
}

###
GET http://localhost:3001/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U2ZWIzZjAzYzllYmIwNDEzNzk5MjUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDMxODY4NDMsImV4cCI6MTc0MzE5NDA0M30.l4MuIBW6ZiOGQWdWp3_NmbacpU2y21Fa3CZH02CCzRA

###
GET http://localhost:3001/api/users/mine
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U2ZWIzZjAzYzllYmIwNDEzNzk5MjUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDMxODY4NDMsImV4cCI6MTc0MzE5NDA0M30.l4MuIBW6ZiOGQWdWp3_NmbacpU2y21Fa3CZH02CCzRA

###
PATCH http://localhost:3001/api/users/company HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U2ZWIzZjAzYzllYmIwNDEzNzk5MjUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDMxODY4NDMsImV4cCI6MTc0MzE5NDA0M30.l4MuIBW6ZiOGQWdWp3_NmbacpU2y21Fa3CZH02CCzRA

{
    "company": {
        "name": "Servitop, SL.",
        "cif": "BXXXXXXXX",
        "street": "Carlos V",
        "number": 22,
        "postal": 28936,
        "city": "Móstoles",
        "province": "Madrid"
    }
}

###

PATCH http://localhost:3001/api/storage HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U2ZWIzZjAzYzllYmIwNDEzNzk5MjUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDMxODY4NDMsImV4cCI6MTc0MzE5NDA0M30.l4MuIBW6ZiOGQWdWp3_NmbacpU2y21Fa3CZH02CCzRA

--boundary123
Content-Disposition: form-data; name="image"; filename="logo.png"
Content-Type: image/jpeg

< ./logo.png
--boundary123--

###
DELETE http://localhost:3001/api/users?soft=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2UyYWY5YjhjZjViMDRiZTA3YjJhYzkiLCJpYXQiOjE3NDMxMDA1NDMsImV4cCI6MTc0MzEwNzc0M30.RaEUbd0URDJdWlPh01cRh_r2KFB9LTnvNrtbWoC-fGc

//Primero solicito recuperar contraseña, cuando hago esto se envía el codigo de verificación a mi 'mail',
//cuando compruebo que el code es correcto se borra la contraseña antigua y se introduce la nueva contraseña que tendrá el user
//solo se puede hacer del user con el token de sesión.

###

POST http://localhost:3001/api/users/guest HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U2ZWIzZjAzYzllYmIwNDEzNzk5MjUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDMxODY4NDMsImV4cCI6MTc0MzE5NDA0M30.l4MuIBW6ZiOGQWdWp3_NmbacpU2y21Fa3CZH02CCzRA

{
    "mail": "InvitadoUno@correo.es",
    "passwd": "A12345678",
    "name": "Pepe",
    "surnames": "Invitado",
    "nif": "40000000W"
}

###
POST http://localhost:3001/api/auth/passPetition
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U2ZWIzZjAzYzllYmIwNDEzNzk5MjUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDMyMzk4MjUsImV4cCI6MTc0MzI0NzAyNX0.bAFkllUcq9mcBSAEnMqH3o6PWxK8QIiIkGIvjnpgn-g

###
POST http://localhost:3001/api/auth/passChange
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U2ZWIzZjAzYzllYmIwNDEzNzk5MjUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDMyMzk4MjUsImV4cCI6MTc0MzI0NzAyNX0.bAFkllUcq9mcBSAEnMqH3o6PWxK8QIiIkGIvjnpgn-g

{
    "verifyCode": "885910",
    "newPasswd": "A8888888"
}