POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "mail": "primer@correo.es",
    "passwd": "A12345678"
}


###
POST http://localhost:3001/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "mail": "comparoCode@correo.es",
    "passwd": "A12345678"
}

###
POST http://localhost:3001/api/verify HTTP/1.1
Content-Type: application/json

{
    "mail": "comparoCode2@correo.es",
    "verifyCode": "655259"
}

###
POST http://localhost:3001/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "mail": "comparoCode2@correo.es",
    "passwd": "A12345678"
}

####

PUT http://localhost:3001/api/users/register HTTP/1.1
Content-Type: application/json

{
    "mail": "comparoCode2@correo.es",
    "name": "José",
    "surnames": "García Pérez",
    "nif": "40000000W"
}

###
GET http://localhost:3001/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2UyYWY5YjhjZjViMDRiZTA3YjJhYzkiLCJpYXQiOjE3NDI5OTI2ODgsImV4cCI6MTc0Mjk5OTg4OH0.Ki6bHv3AWPvwShXzry11Q0rfsmFr6mrcx7uHjaiTpkU


###
PATCH http://localhost:3001/api/users/company HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2UyYWY5YjhjZjViMDRiZTA3YjJhYzkiLCJpYXQiOjE3NDI5OTI2ODgsImV4cCI6MTc0Mjk5OTg4OH0.Ki6bHv3AWPvwShXzry11Q0rfsmFr6mrcx7uHjaiTpkU

{
    "company": {
        "name": "Servitop, SL.",
        "cif": "BXXXXXXXX",
        "street": "Carlos V",
        "number": 22,
        "postal": 28936,
        "city": "Móstoles",
        "province": "Madrid"
    }
}